# Generated by Django 5.2.17 on 2026-09-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0003_remove_project_buyer_id_project_buyer_and_more'),
    ]

    # These operations only update Django's migration state. The canonical
    # Supabase schema already has manager_id/responsible_emp_id/employee_id
    # columns and their foreign keys; issuing the autodetector's remove/add
    # SQL would needlessly drop populated production columns.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name='phase', name='responsible_emp_id'),
                migrations.RemoveField(model_name='project', name='manager_id'),
                migrations.AlterUniqueTogether(
                    name='projectemployee',
                    unique_together={('project', 'employee')},
                ),
                migrations.AddField(
                    model_name='phase',
                    name='responsible_emp',
                    field=models.ForeignKey(blank=True, db_column='responsible_emp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_phases', to='employees.employee'),
                ),
                migrations.AddField(
                    model_name='project',
                    name='manager',
                    field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='employees.employee'),
                ),
                migrations.AddField(
                    model_name='projectemployee',
                    name='employee',
                    field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='project_employee_records', to='employees.employee'),
                ),
                migrations.RemoveField(model_name='projectemployee', name='employee_id'),
            ],
        ),
    ]
